# Generated by Django 4.1.5 on 2023-02-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='clast_name',
            new_name='last_name',
        ),
    ]
